default_platform(:android)

platform :android do

  desc "create git tag and push tag"
  lane :create_git_tag do |options|
    version = options[:version]

    add_git_tag(tag: "#{version}")
    push_git_tags
  end

  desc "gradle clean, install, uploadArchives"
  lane :gradle_tasks do
    gradle(task: "clean")
    gradle(task: "install")
    gradle(task: "uploadArchives")
  end
  
  desc "create github release and upload assets"
  lane :create_release do |options|
    version = options[:version]
    branch = options[:branch]
    changelog_section = options[:changelog_section]
    output_dir = options[:output_dir]
    github_token = options[:github_token]
    set_prerelease = options[:set_prerelease]

    version_changelog = read_changelog(
      changelog_path: 'CHANGELOG.md',
      section_identifier: "[#{changelog_section}]",	
    )

    github_release = set_github_release(
      repository_name: "Iterable/iterable-android-sdk",
      api_token: github_token,
      name: "#{version}",
      tag_name: "#{version}",
      description: version_changelog,
      commitish: "#{branch}",
      is_prerelease: set_prerelease
    )
  end
end

