package com.iterable.iterableapi

/**
 * Created by David Truong dt@iterable.com
 *
 * IterableConstants contains a list of constants used with the Iterable mobile SDK.
 */
object IterableConstants {
    const val ACTION_NOTIF_OPENED = "com.iterable.push.ACTION_NOTIF_OPENED"
    const val ACTION_PUSH_ACTION = "com.iterable.push.ACTION_PUSH_ACTION"
    const val ACTION_PUSH_REGISTRATION = "com.iterable.push.ACTION_PUSH_REGISTRATION"

    //Hosts
    const val BASE_URL_API = "https://api.iterable.com/api/"
    const val BASE_URL_LINKS = "https://links.iterable.com/"

    //API Fields
    const val HEADER_API_KEY           = "Api-Key"
    const val HEADER_SDK_PLATFORM      = "SDK-Platform"
    const val HEADER_SDK_VERSION       = "SDK-Version"
    const val HEADER_SDK_AUTHORIZATION = "Authorization"
    const val HEADER_SDK_AUTH_FORMAT   = "Bearer "
    const val HEADER_SDK_PROCESSOR_TYPE = "SDK-Request-Processor"
    const val KEY_APPLICATION_NAME     = "applicationName"
    const val KEY_CAMPAIGN_ID          = "campaignId"
    const val KEY_CURRENT_EMAIL        = "currentEmail"
    const val KEY_CURRENT_USERID       = "currentUserId"
    const val KEY_DATA_FIELDS          = "dataFields"
    const val KEY_MERGE_NESTED_OBJECTS = "mergeNestedObjects"
    const val KEY_DEVICE               = "device"
    const val KEY_DEVICE_INFO          = "deviceInfo"
    const val KEY_EMAIL                = "email"
    const val KEY_EMAIL_LIST_IDS       = "emailListIds"
    const val KEY_EVENT_NAME           = "eventName"
    const val KEY_ITEMS                = "items"
    const val KEY_NEW_EMAIL            = "newEmail"
    const val KEY_PACKAGE_NAME         = "packageName"
    const val KEY_PLATFORM             = "platform"
    const val KEY_PREFER_USER_ID       = "preferUserId"
    const val KEY_RECIPIENT_EMAIL      = "recipientEmail"
    const val KEY_SEND_AT              = "sendAt"
    const val KEY_CREATED_AT           = "createdAt"
    const val KEY_SENT_AT              = "Sent-At"
    const val KEY_TEMPLATE_ID          = "templateId"
    const val KEY_MESSAGE_CONTEXT      = "messageContext"
    const val KEY_MESSAGE_ID           = "messageId"
    const val KEY_TOKEN                = "token"
    const val KEY_TOTAL                = "total"
    const val KEY_UNSUB_CHANNEL        = "unsubscribedChannelIds"
    const val KEY_UNSUB_MESSAGE        = "unsubscribedMessageTypeIds"
    const val KEY_SUB_MESSAGE          = "subscribedMessageTypeIds"
    const val KEY_USER_ID              = "userId"
    const val KEY_USER                 = "user"
    const val KEY_USER_TEXT            = "userText"
    const val KEY_INBOX_SESSION_ID     = "inboxSessionId"
    const val KEY_EMBEDDED_SESSION_ID     = "id"
    const val KEY_OFFLINE_MODE         = "offlineMode"
    const val KEY_FIRETV = "FireTV"

    //API Endpoint Key Constants
    const val ENDPOINT_DISABLE_DEVICE          = "users/disableDevice"
    const val ENDPOINT_GET_INAPP_MESSAGES      = "inApp/getMessages"
    const val ENDPOINT_INAPP_CONSUME           = "events/inAppConsume"
    const val ENDPOINT_PUSH_TARGET             = "push/target"
    const val ENDPOINT_REGISTER_DEVICE_TOKEN   = "users/registerDeviceToken"
    const val ENDPOINT_TRACK                   = "events/track"
    const val ENDPOINT_TRACK_INAPP_CLICK       = "events/trackInAppClick"
    const val ENDPOINT_TRACK_INAPP_OPEN        = "events/trackInAppOpen"
    const val ENDPOINT_TRACK_INAPP_DELIVERY    = "events/trackInAppDelivery"
    const val ENDPOINT_TRACK_INBOX_SESSION     = "events/trackInboxSession"
    const val ENDPOINT_UPDATE_CART             = "commerce/updateCart"
    const val ENDPOINT_TRACK_PURCHASE          = "commerce/trackPurchase"
    const val ENDPOINT_TRACK_PUSH_OPEN         = "events/trackPushOpen"
    const val ENDPOINT_UPDATE_USER             = "users/update"
    const val ENDPOINT_UPDATE_EMAIL            = "users/updateEmail"
    const val ENDPOINT_UPDATE_USER_SUBS        = "users/updateSubscriptions"
    const val ENDPOINT_TRACK_INAPP_CLOSE       = "events/trackInAppClose"
    const val ENDPOINT_GET_REMOTE_CONFIGURATION = "mobile/getRemoteConfiguration"
    const val ENDPOINT_GET_EMBEDDED_MESSAGES   = "embedded-messaging/messages"
    const val ENDPOINT_TRACK_EMBEDDED_RECEIVED   = "embedded-messaging/events/received"
    const val ENDPOINT_TRACK_EMBEDDED_CLICK   = "embedded-messaging/events/click"
    const val ENDPOINT_TRACK_EMBEDDED_SESSION   = "embedded-messaging/events/session"

    const val PUSH_APP_ID                      = "IterableAppId"
    const val PUSH_GCM_PROJECT_NUMBER          = "GCMProjectNumber"
    const val PUSH_DISABLE_AFTER_REGISTRATION  = "DisableAfterRegistration"

    const val MESSAGING_PUSH_SERVICE_PLATFORM  = "PushServicePlatform"
    const val MESSAGING_PLATFORM_GOOGLE               = "GCM" // Deprecated, only used internally
    const val MESSAGING_PLATFORM_FIREBASE      = "FCM"
    const val MESSAGING_PLATFORM_AMAZON        = "ADM"

    const val IS_GHOST_PUSH        = "isGhostPush"
    const val ITERABLE_DATA_ACTION_IDENTIFIER = "actionIdentifier"
    const val ITERABLE_ACTION_DEFAULT = "default"
    const val ITERABLE_DATA_BADGE  = "badge"
    const val ITERABLE_DATA_BODY   = "body"
    const val ITERABLE_DATA_KEY    = "itbl"
    const val ITERABLE_DATA_DEEP_LINK_URL = "uri"
    const val ITERABLE_DATA_PUSH_IMAGE  = "attachment-url"
    const val ITERABLE_DATA_SOUND  = "sound"
    const val ITERABLE_DATA_TITLE  = "title"
    const val ITERABLE_DATA_ACTION_BUTTONS  = "actionButtons"
    const val ITERABLE_DATA_DEFAULT_ACTION  = "defaultAction"

    //SharedPreferences keys
    const val SHARED_PREFS_FILE = "com.iterable.iterableapi"
    const val SHARED_PREFS_EMAIL_KEY = "itbl_email"
    const val SHARED_PREFS_USERID_KEY = "itbl_userid"
    const val SHARED_PREFS_DEVICEID_KEY = "itbl_deviceid"
    const val SHARED_PREFS_AUTH_TOKEN_KEY = "itbl_authtoken"
    const val SHARED_PREFS_EXPIRATION_SUFFIX = "_expiration"
    const val SHARED_PREFS_OBJECT_SUFFIX = "_object"
    const val SHARED_PREFS_PAYLOAD_KEY = "itbl_payload"
    const val    SHARED_PREFS_PAYLOAD_EXPIRATION_HOURS = 24
    const val SHARED_PREFS_ATTRIBUTION_INFO_KEY = "itbl_attribution_info"
    const val    SHARED_PREFS_ATTRIBUTION_INFO_EXPIRATION_HOURS = 24
    const val SHARED_PREFS_FCM_MIGRATION_DONE_KEY = "itbl_fcm_migration_done"
    const val SHARED_PREFS_SAVED_CONFIGURATION = "itbl_saved_configuration"
    const val SHARED_PREFS_OFFLINE_MODE_KEY = "itbl_offline_mode"
    const val SHARED_PREFS_DEVICE_NOTIFICATIONS_ENABLED = "itbl_notifications_enabled"

    //Action buttons
    const val ITBL_BUTTON_IDENTIFIER        = "identifier"
    const val ITBL_BUTTON_TYPE              = "buttonType"
    const val ITBL_BUTTON_TITLE             = "title"
    const val ITBL_BUTTON_OPEN_APP          = "openApp"
    const val ITBL_BUTTON_REQUIRES_UNLOCK   = "requiresUnlock"
    const val ITBL_BUTTON_ICON              = "icon"
    const val ITBL_BUTTON_INPUT_TITLE       = "inputTitle"
    const val ITBL_BUTTON_INPUT_PLACEHOLDER = "inputPlaceholder"
    const val ITBL_BUTTON_ACTION            = "action"

    //Device
    const val DEVICE_BRAND             = "brand"
    const val DEVICE_MANUFACTURER      = "manufacturer"
    const val DEVICE_SYSTEM_NAME       = "systemName"
    const val DEVICE_SYSTEM_VERSION    = "systemVersion"
    const val DEVICE_MODEL             = "model"
    const val DEVICE_SDK_VERSION       = "sdkVersion"
    const val DEVICE_ID                   = "deviceId"
    const val DEVICE_APP_PACKAGE_NAME     = "appPackageName"
    const val DEVICE_APP_VERSION          = "appVersion"
    const val DEVICE_APP_BUILD            = "appBuild"
    const val DEVICE_NOTIFICATIONS_ENABLED = "notificationsEnabled"
    const val DEVICE_ITERABLE_SDK_VERSION = "iterableSdkVersion"
    const val DEVICE_MOBILE_FRAMEWORK_INFO = "mobileFrameworkInfo"
    const val DEVICE_FRAMEWORK_TYPE       = "frameworkType"

    const val INSTANCE_ID_CLASS        = "com.google.android.gms.iid.InstanceID"
    const val ICON_FOLDER_IDENTIFIER   = "drawable"
    const val NOTIFICATION_ICON_NAME   = "iterable_notification_icon"
    const val NOTIFICAION_BADGING      = "iterable_notification_badging"
    const val NOTIFICATION_COLOR       = "iterable_notification_color"
    const val NOTIFICATION_CHANNEL_NAME = "iterable_notification_channel_name"
    const val DEFAULT_SOUND            = "default"
    const val SOUND_FOLDER_IDENTIFIER  = "raw"
    const val ANDROID_RESOURCE_PATH    = "android.resource://"
    const val ANDROID_STRING           = "string"
    const val MAIN_CLASS               = "mainClass"
    const val REQUEST_CODE             = "requestCode"
    const val ACTION_IDENTIFIER        = "actionIdentifier"
    const val USER_INPUT               = "userInput"

    //Firebase
    const val FIREBASE_SENDER_ID       = "gcm_defaultSenderId"
    const val FIREBASE_MESSAGING_CLASS = "com.google.firebase.messaging.FirebaseMessaging"
    const val FIREBASE_COMPATIBLE      = "firebaseCompatible"
    const val FIREBASE_TOKEN_TYPE      = "tokenRegistrationType"
    const val FIREBASE_INITIAL_UPGRADE = "initialFirebaseUpgrade"

    const val ITBL_DEEPLINK_IDENTIFIER = "/a/[A-Za-z0-9]+"
    const val DATEFORMAT = "yyyy-MM-dd HH:mm:ss"
    const val PICASSO_CLASS = "com.squareup.picasso.Picasso"
    const val LOCATION_HEADER_FIELD = "Location"

    //Embedded Message Constants
    const val ITERABLE_EMBEDDED_MESSAGE_PLACEMENTS  = "placements"
    const val ITERABLE_EMBEDDED_MESSAGE  = "embeddedMessages"
    const val ITERABLE_EMBEDDED_MESSAGE_METADATA = "metadata"
    const val ITERABLE_EMBEDDED_MESSAGE_ELEMENTS = "elements"
    const val ITERABLE_EMBEDDED_MESSAGE_PAYLOAD = "payload"
    const val ITERABLE_EMBEDDED_MESSAGE_ID = "messageId"
    const val ITERABLE_EMBEDDED_MESSAGE_PLACEMENT_ID = "placementId"
    const val ITERABLE_EMBEDDED_MESSAGE_CAMPAIGN_ID = "campaignId"
    const val ITERABLE_EMBEDDED_MESSAGE_IS_PROOF = "isProof"
    const val ITERABLE_EMBEDDED_MESSAGE_TITLE = "title"
    const val ITERABLE_EMBEDDED_MESSAGE_BODY = "body"
    const val ITERABLE_EMBEDDED_MESSAGE_MEDIA_URL = "mediaUrl"
    const val ITERABLE_EMBEDDED_MESSAGE_MEDIA_URL_CAPTION = "mediaUrlCaption"
    const val ITERABLE_EMBEDDED_MESSAGE_DEFAULT_ACTION = "defaultAction"
    const val ITERABLE_EMBEDDED_MESSAGE_BUTTONS = "buttons"
    const val ITERABLE_EMBEDDED_MESSAGE_BUTTON_IDENTIFIER = "buttonIdentifier"
    const val ITERABLE_EMBEDDED_MESSAGE_BUTTON_TARGET_URL = "targetUrl"
    const val ITERABLE_EMBEDDED_MESSAGE_TEXT = "text"
    const val ITERABLE_EMBEDDED_MESSAGE_DEFAULT_ACTION_TYPE = "type"
    const val ITERABLE_EMBEDDED_MESSAGE_DEFAULT_ACTION_DATA = "data"
    const val ITERABLE_EMBEDDED_MESSAGE_BUTTON_ID = "id"
    const val ITERABLE_EMBEDDED_MESSAGE_BUTTON_TITLE = "title"
    const val ITERABLE_EMBEDDED_MESSAGE_BUTTON_ACTION = "action"
    const val ITERABLE_EMBEDDED_MESSAGE_BUTTON_ACTION_TYPE = "type"
    const val ITERABLE_EMBEDDED_MESSAGE_BUTTON_ACTION_DATA = "data"
    const val ITERABLE_EMBEDDED_MESSAGE_TEXT_ID = "id"
    const val ITERABLE_EMBEDDED_MESSAGE_TEXT_TEXT = "text"
    const val ITERABLE_EMBEDDED_MESSAGE_TEXT_LABEL = "label"

    const val ITERABLE_EMBEDDED_SESSION = "session"
    const val ITERABLE_EMBEDDED_SESSION_START = "start"
    const val ITERABLE_EMBEDDED_SESSION_END = "end"
    const val ITERABLE_EMBEDDED_IMPRESSIONS = "impressions"
    const val ITERABLE_EMBEDDED_IMP_DISPLAY_COUNT = "displayCount"
    const val ITERABLE_EMBEDDED_IMP_DISPLAY_DURATION = "displayDuration"

    //In-App Constants
    const val ITERABLE_IN_APP_BGCOLOR_ALPHA    = "alpha"
    const val ITERABLE_IN_APP_BGCOLOR_HEX      = "hex"
    const val ITERABLE_IN_APP_BGCOLOR          = "bgColor"
    const val ITERABLE_IN_APP_BACKGROUND_COLOR = "backgroundColor"
    const val ITERABLE_IN_APP_BACKGROUND_ALPHA = "backgroundAlpha"
    const val ITERABLE_IN_APP_BODY             = "body"
    const val ITERABLE_IN_APP_BUTTON_ACTION    = "action"
    const val ITERABLE_IN_APP_BUTTON_INDEX     = "buttonIndex"
    const val ITERABLE_IN_APP_BUTTONS          = "buttons"
    const val ITERABLE_IN_APP_COLOR            = "color"
    const val ITERABLE_IN_APP_CONTENT          = "content"
    const val ITERABLE_IN_APP_JSON_ONLY        = "jsonOnly"
    const val ITERABLE_IN_APP_COUNT            = "count"
    const val ITERABLE_IN_APP_MAIN_IMAGE       = "mainImage"
    const val ITERABLE_IN_APP_MESSAGE          = "inAppMessages"
    const val ITERABLE_IN_APP_TEXT             = "text"
    const val ITERABLE_IN_APP_TITLE            = "title"
    const val ITERABLE_IN_APP_TYPE             = "displayType"
    const val ITERABLE_IN_APP_CLICKED_URL      = "clickedUrl"
    const val ITERABLE_IN_APP_HTML             = "html"
    const val ITERABLE_IN_APP_CREATED_AT       = "createdAt"
    const val ITERABLE_IN_APP_EXPIRES_AT       = "expiresAt"
    const val ITERABLE_IN_APP_LEGACY_PAYLOAD   = "payload"
    const val ITERABLE_IN_APP_CUSTOM_PAYLOAD   = "customPayload"
    const val ITERABLE_IN_APP_TRIGGER          = "trigger"
    const val ITERABLE_IN_APP_TRIGGER_TYPE     = "type"
    const val ITERABLE_IN_APP_PRIORITY_LEVEL   = "priorityLevel"
    const val ITERABLE_IN_APP_SAVE_TO_INBOX    = "saveToInbox"
    const val ITERABLE_IN_APP_SILENT_INBOX     = "silentInbox"
    const val ITERABLE_IN_APP_INBOX_METADATA   = "inboxMetadata"
    const val ITERABLE_IN_APP_DISPLAY_SETTINGS = "inAppDisplaySettings"
    const val ITERABLE_IN_APP_PROCESSED        = "processed"
    const val ITERABLE_IN_APP_CONSUMED         = "consumed"
    const val ITERABLE_IN_APP_READ             = "read"
    const val ITERABLE_IN_APP_LOCATION         = "location"
    const val ITERABLE_IN_APP_CLOSE_ACTION     = "closeAction"
    const val ITERABLE_IN_APP_DELETE_ACTION    = "deleteAction"
    const val ITERABLE_INBOX_SESSION_START              = "inboxSessionStart"
    const val ITERABLE_INBOX_SESSION_END                = "inboxSessionEnd"
    const val ITERABLE_INBOX_START_TOTAL_MESSAGE_COUNT  = "startTotalMessageCount"
    const val ITERABLE_INBOX_START_UNREAD_MESSAGE_COUNT = "startUnreadMessageCount"
    const val ITERABLE_INBOX_END_TOTAL_MESSAGE_COUNT    = "endTotalMessageCount"
    const val ITERABLE_INBOX_END_UNREAD_MESSAGE_COUNT   = "endUnreadMessageCount"
    const val ITERABLE_INBOX_START_ACTION               = "startAction"
    const val ITERABLE_INBOX_END_ACTION                 = "endAction"
    const val ITERABLE_INBOX_IMPRESSIONS                = "impressions"
    const val ITERABLE_INBOX_IMP_DISPLAY_COUNT          = "displayCount"
    const val ITERABLE_INBOX_IMP_DISPLAY_DURATION       = "displayDuration"
    const val ITERABLE_IN_APP_SHOULD_ANIMATE            = "shouldAnimate"
    const val ITERABLE_IN_APP_ANIMATION_DURATION           = 500
    const val ITERABLE_IN_APP_BACKGROUND_ANIMATION_DURATION = 300

    const val EXPONENTIAL_FACTOR                              = 2

    const val ITERABLE_IN_APP_PRIORITY_LEVEL_LOW           = 400.0
    const val ITERABLE_IN_APP_PRIORITY_LEVEL_MEDIUM        = 300.0
    const val ITERABLE_IN_APP_PRIORITY_LEVEL_HIGH          = 200.0
    const val ITERABLE_IN_APP_PRIORITY_LEVEL_CRITICAL      = 100.0
    const val ITERABLE_IN_APP_PRIORITY_LEVEL_UNASSIGNED    = 300.5

    const val ITERABLE_IN_APP_TYPE_BOTTOM  = "BOTTOM"
    const val ITERABLE_IN_APP_TYPE_CENTER  = "MIDDLE"
    const val ITERABLE_IN_APP_TYPE_FULL    = "FULL"
    const val ITERABLE_IN_APP_TYPE_TOP     = "TOP"

    const val ITERABLE_IN_APP_INBOX_TITLE      = "title"
    const val ITERABLE_IN_APP_INBOX_SUBTITLE   = "subtitle"
    const val ITERABLE_IN_APP_INBOX_ICON       = "icon"

    // Custom actions handled by the SDK
    const val ITERABLE_IN_APP_ACTION_DELETE    = "delete"

    //Offline operation
    const val OFFLINE_TASKS_LIMIT                = 1000

    // URL schemes
    const val URL_SCHEME_ITBL = "itbl://"
    const val URL_SCHEME_ITERABLE = "iterable://"
    const val URL_SCHEME_ACTION = "action://"

    const val ITBL_KEY_SDK_VERSION = "SDKVersion"
    const val ITBL_PLATFORM_ANDROID = "Android"
    const val ITBL_PLATFORM_OTT = "OTT"
    const val ITBL_KEY_SDK_VERSION_NUMBER = BuildConfig.ITERABLE_SDK_VERSION
    const val ITBL_SYSTEM_VERSION = "systemVersion"

    const val NO_MESSAGES_TITLE = "noMessagesTitle"
    const val NO_MESSAGES_BODY = "noMessagesBody"
}