on:
  issues:
    types: [opened]

name: Create Jira Issue

jobs:
  build:
    runs-on: ubuntu-latest
    name: Create Jira Issue
    steps:
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_ILYA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_ILYA_API_TOKEN }}

      - name: Create
        id: create
        uses: atlassian/gajira-create@v3
        with:
          project: MOB
          issuetype: Bug
          summary: "${{ github.repository }}: #${{ github.event.issue.number }} by ${{ github.event.issue.user.login }}: ${{ github.event.issue.title }}"
          description: ${{ github.event.issue.body }}
          fields: '{"customfield_11268": {"id": "10668"} }'
